apiVersion: v1
kind: Endpoints
metadata:
  name: jenkins-service
  namespace: jenkins
subsets:
- addresses:
  - ip: 192.168.49.4
  ports:
  - port: 8080
    name: http
  - port: 50000
    name: agent
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  ports:
  - port: 8080        # Jenkins Web UI port
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 50000       # Jenkins agent TCP port
    targetPort: 50000
    protocol: TCP
    name: agent
  clusterIP: None  # Headless service (optional, or omit for default)

