apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: ExternalName
  externalName: jenkins
  ports:
    - port: 8080
      name: http
    - port: 50000
      name: agent


